#
# Tesseract OCR Runtime Environment - Docker Container
#

FROM ubuntu:18.04

RUN apt-get update && apt-get install -y software-properties-common
RUN apt-get update && apt-get install -y tesseract-ocr-all 

RUN mkdir -p /workspace && mkdir -p /workspace/output && mkdir -p /workspace/images
WORKDIR /workspace

VOLUME ["./images/","/workspace/images"]
VOLUME ["./output/","/workspace/output"]

#CMD ["tesseract"]